name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up JDK 8
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 8
        distribution: adopt
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/maven-wrapper.properties') }}
        # perfect match for the cache key:
        # if a POM changes we start with a brand new cache
    - name: Download Maven dependencies
      run: >
        ./mvnw dependency:go-offline

  build:
    needs: cache-dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up JDK 8
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 8
        distribution: adopt
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-build-${{ hashFiles('**/pom.xml', '**/maven-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: ./mvnw verify
